# Generated by Django 5.0.8 on 2024-08-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_articles_delete_modelname'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='subtitle',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
