# Generated by Django 5.0.8 on 2024-08-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0003_articles_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='subtitle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
