# Generated by Django 5.0.8 on 2024-09-16 11:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0005_alter_articles_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
